### ISSUE TITLE
Task list support

### ISSUE THREAD

**Issue by gozzarda** [kivikakk/cmark-gfm-hs#15]
Does this library support GFM task lists? I can't see how, if so.

**Comment by kivikakk** [comment]
It doesn't! I'd happily accept a PR to add support, it just needs to be exposed.

**Comment by gillchristian** [comment]
I'm not familiar with either Haskell bindings and the underlying C library but it's something I'd like to be supported, so I will give it a try.

**Comment by gillchristian** [comment]
Since #16 was merged this can be closed 😅

**Comment by kivikakk** [comment]
Of course! Thanks again!
