### ISSUE TITLE
[security] update C code to cmark-gfm-0.29.0.gfm.3

### ISSUE THREAD

**Issue by juhp** [kivikakk/cmark-gfm-hs#21]
Recently a [vulnerability](https://github.com/github/cmark-gfm/security/advisories/GHSA-mc3g-88wq-6f4x) was fixed in the C cmark-gfm library.
It would be really good if the copy in the Haskell library here could be updated with the fix and a new release made.

**Comment by kivikakk** [comment]
[0.2.3 is on Hackage](https://hackage.haskell.org/package/cmark-gfm-0.2.3). Thanks!

**Comment by juhp** [comment]
Thank you!
