### ISSUE TITLE
not big-endian-safe

### ISSUE THREAD

**Issue by clinty** [kivikakk/cmark-gfm-hs#6]
```
### Error in:   8
Unknown node type 49163
CallStack (from HasCallStack):
  error, called at CMarkGFM.hsc:354:15 in cmark-gfm-0.1.3-zttrehBslGGG4SIxEjYg3:CMarkGFM

Cases: 16  Tried: 9  Errors: 1  Failures: 0
Cases: 16  Tried: 10  Errors: 1  Failures: 0
Cases: 16  Tried: 11  Errors: 1  Failures: 0
Cases: 16  Tried: 12  Errors: 1  Failures: 0
Cases: 16  Tried: 13  Errors: 1  Failures: 0
                                            
### Error in:   13
Unknown node type 32779
CallStack (from HasCallStack):
  error, called at CMarkGFM.hsc:354:15 in cmark-gfm-0.1.3-zttrehBslGGG4SIxEjYg3:CMarkGFM

Cases: 16  Tried: 14  Errors: 2  Failures: 0
Cases: 16  Tried: 15  Errors: 2  Failures: 0
                                            
Cases: 16  Tried: 16  Errors: 2  Failures: 0
Test suite test-cmark-gfm: FAIL
```

**Comment by juhp** [comment]
I think I just hit this on Fedora too:

https://koji.fedoraproject.org/koji/taskinfo?taskID=27259418

compared to cmark-hs:
https://koji.fedoraproject.org/koji/taskinfo?taskID=24790806

**Comment by LocutusOfBorg** [comment]
Hello, ping @kivikakk

**Comment by kivikakk** [comment]
Thanks for the ping; this isn't ideal.

Would someone like to open a PR to fix this? I don't have the time on my hands (nor a BE machine) to investigate.

**Comment by LocutusOfBorg** [comment]
unfortunately I don't speak haskell, but I can test any patch you give me, or help you in setup a qemu machine to test it
(a matter of "pbuilder-dist s390x create && pbuilder-dist s390x login")

and then build it :)

**Comment by LocutusOfBorg** [comment]
this is blocking right now pandoc, and a lot of packages building documentation on BE machines...

**Comment by kivikakk** [comment]
As I mentioned, I don't have the time, so I won't be able to make a fix here myself.

**Comment by LocutusOfBorg** [comment]
I get this, but maybe you can give me some "debugging hint" or a patch that prints variables before and after the issue, so I can debug it myself?

**Comment by kivikakk** [comment]
I gave it a try so I could get a test running for #7 — getting the necessary setup just to _run_ `pbuilder-dist` was a huge effort, and unfortunately the s390x creation on my machine outright failed with very little useful output.

```
I: Extracting util-linux...
I: Extracting liblzma5...
I: Extracting zlib1g...
I: Running command: chroot . /debootstrap/debootstrap --second-stage
I: Keyring file not available at /usr/share/keyrings/debian-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
W: Failure trying to run:  /sbin/ldconfig
W: See //debootstrap/debootstrap.log for details
E: qemu-debootstrap failed
W: Aborting with an error
I: cleaning the build env 
I: removing directory /var/cache/pbuilder/build//18101 and its subdirectories
```

I went another route and did a manual qemu setup and Debian install instead, which took a few hours. I'm now compiling `cmark-gfm-hs`'s dependencies, but it's taking a lonnnng time 😅

**Comment by kivikakk** [comment]
(Also, your `pbuilder-dist` invocation examples were missing the mandatory `distribution` argument!)

**Comment by kivikakk** [comment]
I've hit the end of my day and `cmark-gfm-hs` itself is still compiling, so I'll come back to this next week.

**Comment by juhp** [comment]
I tested the change successfully on Fedora 29 ppc64 and s390x:
https://kojipkgs.fedoraproject.org//work/tasks/735/27940735/build.log
https://kojipkgs.fedoraproject.org//work/tasks/734/27940734/build.log

https://koji.fedoraproject.org/koji/taskinfo?taskID=27940955 is a test build on all Fedora arch's for more confidence.

**Comment by LocutusOfBorg** [comment]
the fix now has migrated together with the whole haskell stack in Ubuntu Cosmic!

**Comment by kivikakk** [comment]
0.1.4 has been released with this fix!
